# Generated by Django 3.1.1 on 2020-09-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('type', models.BooleanField(verbose_name='Is Engineer (default: Expert)')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=45, verbose_name='Phone')),
                ('address', models.CharField(max_length=254, verbose_name='Address')),
                ('about', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='About')),
                ('avatar', models.ImageField(blank=True, default=None, max_length=254, null=True, upload_to='images/company/%Y/%m/%d/', verbose_name='Avatar')),
                ('is_inactive', models.BooleanField(default=False, verbose_name='Is inactive?')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
