# Generated by Django 3.1.1 on 2020-09-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=254, upload_to='images/slope/engineer/%Y/%m/%d/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('is_inactive', models.BooleanField(default=False, verbose_name='Is inactive')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slope.order', verbose_name='Order')),
            ],
        ),
    ]
